### ISSUE TITLE
Reference issue

### ISSUE THREAD

**Issue by remyferre** [remyferre/octokit-test#12]
some text #11 text again
pull requests #10  #9  
other issues #7  #3 #8 #6  #4

**Comment by remyferre** [comment]
Reference #11 again

**Comment by lvangool** [comment]
This another comment referencing https://github.com/remyferre/octokit-test/issues/11

**Comment by lvangool** [comment]
another reference (to 10 this time) https://github.com/remyferre/octokit-test/pull/10
